# Generated by Django 5.1 on 2024-08-09 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField()),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='mecanica.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField()),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='mecanica.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut_empleado', models.CharField(max_length=10, unique=True, verbose_name='rut_empleado')),
                ('username_empleado', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario Empleado')),
                ('primer_nombre_empleado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Primer Nombre Empleado')),
                ('segundo_nombre_empleado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo Nombre Empleado')),
                ('apellido_paterno_empleado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Paterno Empleado')),
                ('apellido_materno_empleado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno Empleado')),
                ('fecha_nacimiento_empleado', models.DateField(verbose_name='Fecha de Nacimiento Empleado')),
                ('telefono_empleado', models.CharField(blank=True, max_length=45, null=True, verbose_name='Telefono de Empleado')),
                ('email_empleado', models.EmailField(blank=True, max_length=45, null=True, verbose_name='Correo de Empleado')),
                ('region_empleado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Region de Empleado')),
                ('ciudad_empleado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad de Empleado')),
                ('direccion_empleado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion de Empleado')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='mecanica.genero')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
