# Generated by Django 5.1 on 2024-08-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_genero',
        ),
        migrations.RemoveField(
            model_name='usuario_empleado',
            name='id_genero',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
